app:
  hostname: "localhost"

rabbitmq:
  queue:
    name: "transaction_queue"
    durable: false
    exclusive: false
    auto_delete: false
  prefetch_count: 1

redis:
  port: 6379
  max-total: 20
  max-idle: 10
  min-idle: 5
  min-evictable-idle-sec: 60
  time-between-eviction-runs-sec: 30
  bloc-when-exhausted: true

transaction:
  timeout-min: 5